#! /bin/bash -eu
#
# Release Stackup

cd $(dirname $0)/..

REPOSITORY=realestate/stackup
VERSION=$(ruby -r ./lib/stackup/version.rb -e 'puts Stackup::VERSION')

echo "--- Check that we're releasing from master"
git fetch origin
git diff origin/master --exit-code

echo "--- Build Docker image"
docker build .

echo "--- Releasing gem"
docker run --rm -itw /cwd -v "$PWD:/cwd" ruby:2.6-alpine@sha256:44dcc51eb5dd33ea70abf2450e06a29093b30b880280b6b09fb58dd65b416b3b auto/release-in-docker

echo "--- Releasing Docker image"
docker build -t ${REPOSITORY}:latest .
docker tag ${REPOSITORY}:latest ${REPOSITORY}:${VERSION}
docker push ${REPOSITORY}:${VERSION}
docker push ${REPOSITORY}:latest
