#! /bin/bash -eu
#
# Release Stackup

cd $(dirname $0)/..

rm -f stackup-*.gem

echo "--- Check that we're releasing from main"
git fetch origin
git diff origin/main --exit-code

echo "--- Releasing gem"
docker run --rm -itw /cwd -v "$PWD:/cwd" ruby:2.6-alpine auto/release-in-docker
