require "stackup/rake_tasks"

Stackup::RakeTasks.new("demo") do |t|
  t.stack = ENV.fetch("STACKUP_DEMO_STACK", "stackup-demo")
  t.template = "template.json"
  t.parameters = "parameters-verbose.json"
  t.tags = {
    "environment" => "dev",
    "team" => "rea-oss"
  }
  t.capabilities = [
    "CAPABILITY_IAM",
    "CAPABILITY_NAMED_IAM"
  ]
end
