require "stackup/rake_tasks"

Stackup::RakeTasks.new("demo") do |t|
  t.stack = ENV.fetch("STACKUP_DEMO_STACK", "stackup-demo")
  t.template = "template.json"
  t.parameters = "parameters-verbose.json"
  t.tags = "tags.yml"
end
